import { languageCatalog, languagePackages } from './data/languages.js';
import { loadProfile, saveProfile, languageProgress, updateLanguageProgress, rewardPractice } from './modules/storage.js';
import { currentSession, signUp, signIn, signOut, readProgress, writeProgress } from './modules/cloud.js';

const root = document.querySelector('#app');
let profile = loadProfile();
let view = profile.account ? (profile.selectedLanguage ? 'home' : 'languages') : 'auth';
let session = null;
let languageTarget = 'learning';
let authMode = 'choice';
let cloudUser = null;

const escape = value => String(value).replace(/[&<>"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;' }[char]));
const shuffle = values => [...values].sort(() => Math.random() - .5);
const pack = () => languagePackages[profile.learningLanguage || profile.selectedLanguage];
const ui = () => pack().ui;
const baseUi = () => languagePackages.nl.ui;
const languageFlags = language => `<span class="flag-set" aria-label="${escape(language.name)}">${(language.flagCodes || []).map(code => `<span class="country-flag flag-${code}" aria-hidden="true"></span>`).join('')}</span>`;
const games = () => pack()?.games || [];

function speak(text, locale = pack()?.metadata.locale) {
  if (!('speechSynthesis' in window)) return;
  speechSynthesis.cancel();
  const say = () => { const voices = speechSynthesis.getVoices(); const languageCode = locale?.split('-')[0]?.toLowerCase(); const voice = voices.find(item => item.lang.toLowerCase().startsWith(languageCode)) || voices.find(item => item.name.toLowerCase().includes(languageCode === 'fa' ? 'persian' : languageCode)); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = voice?.lang || locale || document.documentElement.lang; utterance.rate = .78; if (voice) utterance.voice = voice; speechSynthesis.resume(); speechSynthesis.speak(utterance); };
  speechSynthesis.getVoices().length ? say() : speechSynthesis.addEventListener('voiceschanged', say, { once: true });
}

async function syncCloudProgress() { const language = pack(); if (!cloudUser || !language) return; const rows = (await readProgress(cloudUser.id)).filter(row => row.level >= 1 && row.level <= language.curriculum.length); const progress = languageProgress(profile, language.metadata.id); if (!rows.length && (progress.completed.length || progress.wordIndex)) { for (const lessonIndex of progress.completed) await writeProgress(cloudUser.id, lessonIndex + 1, 0, true); await writeProgress(cloudUser.id, progress.activeLesson + 1, progress.wordIndex || 0, progress.completed.includes(progress.activeLesson)); return; } const completed = rows.filter(row => row.completed).map(row => row.level - 1); const active = rows.filter(row => !row.completed).sort((a, b) => new Date(b.updated_at) - new Date(a.updated_at))[0]; updateLanguageProgress(profile, language.metadata.id, { completed, activeLesson: active ? Math.max(0, active.level - 1) : progress.activeLesson, wordIndex: active?.word_index || 0 }); }
async function persistCloudProgress() { if (!cloudUser || !pack() || !session) return; const progress = languageProgress(profile, pack().metadata.id); const currentLevel = session.lessonIndex + 1; await writeProgress(cloudUser.id, currentLevel, progress.activeLesson === session.lessonIndex ? progress.wordIndex : 0, progress.completed.includes(session.lessonIndex)); }
function renderAuth() {
  const choosing = authMode === 'choice';
  const login = authMode === 'login';
  if (choosing) {
    root.innerHTML = `<main class="screen account-screen"><section class="hero auth-choice"><div class="eyebrow">Lumio</div><h1>Welkom!</h1><p>Begin jouw leeravontuur.</p><div class="account-choices"><button class="choice-button guest-choice" data-action="guest"><span class="choice-icon" aria-hidden="true">▶</span><span><strong>Speel als gast</strong><small>Begin meteen met oefenen</small></span></button><button class="choice-button account-choice" data-action="signup"><span class="choice-icon" aria-hidden="true">★</span><span><strong>Maak een account</strong><small>Bewaar jouw voortgang</small></span></button></div><button class="login-link" data-action="login">Al een account? <strong>Log in</strong></button></section></main>`;
    root.querySelector('[data-action="signup"]').addEventListener('click', () => { authMode = 'signup'; render(); });
    root.querySelector('[data-action="login"]').addEventListener('click', () => { authMode = 'login'; render(); });
    root.querySelector('[data-action="guest"]').addEventListener('click', () => { cloudUser = null; profile.account = null; saveProfile(profile); view = 'languages'; render(); });
    return;
  }
  root.innerHTML = `<main class="screen account-screen"><section class="hero auth-form-card"><button class="back-auth" data-action="back-auth" aria-label="Terug">←</button><div class="eyebrow">Lumio</div><h1>${login ? 'Welkom terug' : 'Maak een account'}</h1><p>${login ? 'Ga verder met jouw leerreis.' : 'Bewaar de groei van je leerheld voor later.'}</p><form id="auth-form" class="auth-form"><label>E-mailadres<input id="auth-email" type="email" autocomplete="email" required placeholder="jij@voorbeeld.nl"></label><label>Wachtwoord<input id="auth-password" type="password" minlength="4" required placeholder="minimaal 4 tekens"></label><button class="button primary" type="submit">${login ? 'Inloggen' : 'Account maken'}</button></form><p class="auth-message" id="auth-message"></p><button class="login-link" data-action="auth-mode">${login ? 'Nog geen account? Maak er een' : 'Al een account? Log in'}</button></section></main>`;
  root.querySelector('#auth-form').addEventListener('submit', async event => { event.preventDefault(); const email = root.querySelector('#auth-email').value.trim().toLowerCase(); const password = root.querySelector('#auth-password').value; const message = root.querySelector('#auth-message'); message.textContent = login ? 'Inloggen…' : 'Account maken…'; const result = login ? await signIn(email, password) : await signUp(email, password); if (result.error) { message.textContent = result.error.message; return; } if (!result.data.session) { message.textContent = 'Controleer je e-mail en bevestig je account. Daarna kun je inloggen.'; return; } cloudUser = result.data.user; profile.account = { email, provider: 'supabase' }; saveProfile(profile); await syncCloudProgress(); view = profile.selectedLanguage ? 'home' : 'languages'; render(); });
  root.querySelector('[data-action="auth-mode"]').addEventListener('click', () => { authMode = login ? 'signup' : 'login'; render(); });
  root.querySelector('[data-action="back-auth"]').addEventListener('click', () => { authMode = 'choice'; render(); });
}

function header() { return `<header class="topbar"><button class="brand" data-action="languages" aria-label="Lumio">Lu<span>mio</span></button><div class="stat-row"><button class="chip" data-action="parent" aria-label="Ouders">👨‍👩‍👧</button><span class="chip">🔥 ${profile.rewards.streak || 0}</span><span class="chip">⭐ ${profile.rewards.stars || 0}</span></div></header>`; }

function renderLanguages() {
  const text = baseUi();
  root.innerHTML = `<main class="screen"><section class="hero"><div class="eyebrow">Lumio</div><h1>${text.chooseWorld}</h1><p>${text.languageIntro}</p><div class="language-grid">${languageCatalog.map(language => { const unavailable = language.status !== 'ready' && languageTarget !== 'native'; return `<article class="language-card"><button class="language-select" data-language="${language.id}" ${unavailable ? 'disabled' : ''}>${languageFlags(language)}<strong>${escape(language.nativeName)}</strong>${unavailable ? `<span class="badge">${text.comingSoon}</span>` : ''}</button><button class="speaker" data-say="${language.id}" aria-label="${text.listen} ${escape(language.nativeName)}">🔊</button></article>`; }).join('')}</div></section></main>`;
  root.querySelectorAll('[data-language]').forEach(button => button.addEventListener('click', () => { const id = button.dataset.language; if (languageTarget === 'native') profile.homeLanguage = id; else { profile.selectedLanguage = id; profile.learningLanguage = id; profile.selectedGame = null; } saveProfile(profile); view = languageTarget === 'native' ? 'home' : 'games'; languageTarget = 'learning'; speak(languageCatalog.find(item => item.id === id).nativeName, languageCatalog.find(item => item.id === id).locale); render(); }));
  root.querySelectorAll('[data-say]').forEach(button => button.addEventListener('click', () => { const language = languageCatalog.find(item => item.id === button.dataset.say); speak(language.nativeName, language.locale); }));
}

function renderGames() {
  const language = pack(); const text = ui();
  root.innerHTML = `${header()}<main class="screen"><section class="hero game-picker"><button class="back game-picker-back" data-action="languages">← ${text.back}</button><div class="eyebrow">${language.metadata.nativeName}</div><h1>Kies een spel</h1><p>Kies hoe je vandaag wilt oefenen.</p><div class="game-grid">${games().map(game => `<button class="game-choice ${game.status !== 'ready' ? 'coming-soon' : ''}" data-game="${game.id}" ${game.status !== 'ready' ? 'disabled aria-disabled="true"' : ''}><span class="game-choice-icon" aria-hidden="true">${game.icon}</span><span><strong>${game.title}</strong><small>${game.description}</small></span>${game.status !== 'ready' ? `<em>${text.comingSoon}</em>` : '<span class="game-choice-arrow" aria-hidden="true">→</span>'}</button>`).join('')}</div></section></main>${adBanner()}`;
  root.querySelector('[data-action="languages"]').addEventListener('click', () => { view = 'languages'; render(); });
  root.querySelectorAll('[data-game]').forEach(button => button.addEventListener('click', () => { profile.selectedGame = button.dataset.game; saveProfile(profile); view = 'home'; render(); }));
  bindHeader();
}

function renderHome() {
  const language = pack(); const progress = languageProgress(profile, language.metadata.id); const completed = progress.completed.length;
  root.innerHTML = `${header()}<main class="screen"><section class="home-grid"><div class="welcome"><div class="eyebrow" style="color:#e9e5ff">${language.metadata.flag} ${language.metadata.nativeName}</div><h1>${ui().hello}</h1><p>${ui().dailyIntro}</p><button class="daily" data-action="daily">▶ ${ui().daily}</button></div><aside class="reward"><div class="eyebrow">${ui().growth}</div><div class="stars">${'⭐'.repeat(Math.min(3, Math.max(1, profile.rewards.stars || 1)))}</div><strong>${completed} / ${language.curriculum.length} ${ui().worlds}</strong><div class="progress"><span style="width:${completed / language.curriculum.length * 100}%"></span></div></aside></section><div class="level-heading"><button class="back" data-action="games">← Spellen</button><div><div class="eyebrow">Woordbouwers</div><h2>Kies een niveau</h2></div></div><section class="lesson-list" aria-label="${ui().worlds}">${language.curriculum.map((lesson, index) => { const locked = index > completed; return `<button class="lesson" data-lesson="${index}" ${locked ? 'disabled aria-disabled="true"' : ''}><span class="lesson-icon">${locked ? '🔒' : lesson.icon}</span><span><strong>${lesson.title}</strong><small>${lesson.skill === 'letter' ? ui().sounds : ui().building}</small></span><span class="lesson-progress">${progress.completed.includes(index) ? '✓' : `${Math.min(10, progress.activeLesson === index ? progress.wordIndex || 0 : 0)}/10`}</span></button>`; }).join('')}</section></main>${adBanner()}`;
  root.querySelector('[data-action="daily"]').addEventListener('click', () => startLesson(progress.activeLesson || 0));
  root.querySelector('[data-action="games"]').addEventListener('click', () => { view = 'games'; render(); });
  root.querySelectorAll('[data-lesson]').forEach(button => button.addEventListener('click', () => startLesson(Number(button.dataset.lesson))));
  bindHeader();
}

function adBanner() { const text = pack() ? ui() : baseUi(); return profile.preferences.adsEnabled ? `<aside class="ad-banner" aria-label="${text.ad}"><span>${text.ad}</span> ${text.adMessage}</aside>` : ''; }

function startLesson(index) {
  const language = pack(); const progress = languageProgress(profile, language.metadata.id); const lesson = language.curriculum[index];
  const wordIndex = progress.activeLesson === index ? (progress.wordIndex || 0) : 0;
  session = { lessonIndex: index, wordIndex: Math.min(wordIndex, lesson.words.length - 1), picks: [], pickButtons: [], mistakes: 0, hintUsed: false, solved: false };
  view = 'game'; render();
}

function renderGame() {
  const language = pack(); const lesson = language.curriculum[session.lessonIndex]; const item = lesson.words[session.wordIndex]; const letters = shuffle([...item.word, ...shuffle(language.alphabet.filter(letter => !item.word.includes(letter))).slice(0, 3)]);
  root.innerHTML = `${header()}<main class="screen game"><div class="game-head"><button class="back" data-action="home">← ${ui().back}</button><div class="progress"><span style="width:${session.wordIndex / lesson.words.length * 100}%"></span></div><span class="count">${session.wordIndex + 1}/10</span></div><section class="game-card"><div class="eyebrow">${lesson.title}</div><div class="picture" role="img" aria-label="${item.word}">${item.emoji}</div><p class="instruction">${lesson.skill === 'letter' ? ui().find : ui().build}</p><div class="answer" id="answer">${'_ '.repeat(item.word.length)}</div><p class="feedback" id="feedback">${ui().gameIntro}</p><div class="letters" id="letters">${letters.map((letter, index) => `<button class="letter" data-letter="${letter}" data-index="${index}">${letter}</button>`).join('')}</div><div class="controls"><button class="button soft" data-action="listen">🔊 ${ui().listen}</button><button class="button soft" data-action="hint">💡 ${ui().hint}</button><button class="button soft" data-action="undo" disabled>⌫</button><button class="button primary" data-action="check" disabled>${ui().check}</button></div></section></main>${adBanner()}`;
  bindHeader();
  root.querySelector('[data-action="home"]').addEventListener('click', async () => { updateLanguageProgress(profile, language.metadata.id, { activeLesson: session.lessonIndex, wordIndex: session.wordIndex }); await persistCloudProgress(); view = 'home'; render(); });
  root.querySelector('[data-action="listen"]').addEventListener('click', () => speak(item.word));
  root.querySelector('[data-action="hint"]').addEventListener('click', event => useHint(item, event.currentTarget));
  root.querySelector('[data-action="undo"]').addEventListener('click', undoPick);
  root.querySelector('[data-action="check"]').addEventListener('click', () => check(item, lesson));
  root.querySelectorAll('[data-letter]').forEach(button => button.addEventListener('click', () => selectLetter(button, item)));
}

function selectLetter(button, item) { if (session.solved || button.classList.contains('selected') || session.picks.length >= item.word.length) return; const expected = item.word[session.picks.length]; if (button.dataset.letter !== expected) { button.classList.add('wrong'); speak(button.dataset.letter); setTimeout(() => button.classList.remove('wrong'), 650); return; } button.classList.add('selected', 'correct'); session.picks.push(button.dataset.letter); session.pickButtons.push(button); updateAnswer(item); }
function updateAnswer(item) { root.querySelector('#answer').textContent = session.picks.join(' ') + ' ' + '_ '.repeat(item.word.length - session.picks.length); root.querySelector('[data-action="undo"]').disabled = !session.picks.length; root.querySelector('[data-action="check"]').disabled = session.picks.length !== item.word.length; }
function undoPick() { const button = session.pickButtons.pop(); if (button) button.classList.remove('selected'); session.picks.pop(); const item = pack().curriculum[session.lessonIndex].words[session.wordIndex]; updateAnswer(item); }
function useHint(item, button) { if (session.hintUsed) return; const target = [...root.querySelectorAll('[data-letter]')].find(node => node.dataset.letter === item.word[session.picks.length] && !node.classList.contains('selected')); if (target) target.classList.add('hinted'); session.hintUsed = true; button.disabled = true; root.querySelector('#feedback').textContent = `${ui().listenPrompt} ${item.word[session.picks.length]}`; speak(item.word[session.picks.length]); }
async function check(item, lesson) { const feedback = root.querySelector('#feedback'); if (session.solved) return nextWord(lesson); if (session.picks.join('') === item.word) { session.solved = true; session.pickButtons.forEach(button => button.classList.add('correct')); feedback.className = 'feedback success celebrate'; feedback.textContent = `${ui().great} ⭐`; root.querySelector('[data-action="check"]').textContent = `✅ ${ui().next}`; root.querySelector('[data-action="undo"]').disabled = true; rewardPractice(profile); await persistCloudProgress(); speak(ui().great); } else { session.mistakes += 1; feedback.className = 'feedback error'; session.pickButtons.forEach(button => button.classList.add('wrong')); if (session.mistakes >= 3) { feedback.textContent = ui().restart; setTimeout(() => { session = null; view = 'home'; render(); }, 1100); } else { feedback.textContent = `${ui().tryAgain} (${3 - session.mistakes})`; setTimeout(() => session.pickButtons.forEach(button => button.classList.remove('wrong')), 650); session.picks = []; session.pickButtons.forEach(button => button.classList.remove('selected', 'correct')); session.pickButtons = []; updateAnswer(item); speak(item.word); } } }
async function nextWord(lesson) { const language = pack(); const progress = languageProgress(profile, language.metadata.id); if (session.wordIndex >= lesson.words.length - 1) { const completed = [...new Set([...progress.completed, session.lessonIndex])]; updateLanguageProgress(profile, language.metadata.id, { completed, activeLesson: Math.min(session.lessonIndex + 1, language.curriculum.length - 1), wordIndex: 0 }); await persistCloudProgress(); session = null; view = 'home'; render(); return; } session.wordIndex += 1; session.picks = []; session.pickButtons = []; session.solved = false; session.hintUsed = false; updateLanguageProgress(profile, language.metadata.id, { activeLesson: session.lessonIndex, wordIndex: session.wordIndex }); await persistCloudProgress(); render(); }

function renderParent() { const language = pack(); const homeLanguage = languageCatalog.find(item => item.id === profile.homeLanguage); const progress = languageProgress(profile, language.metadata.id); root.innerHTML = `${header()}<main class="screen parent"><button class="back" data-action="home">← ${ui().back}</button><div class="eyebrow">${ui().parents}</div><h1>${ui().parentTitle}</h1><div class="parent-grid"><div class="metric"><strong>${progress.completed.length}</strong><small>${ui().worldsDone}</small></div><div class="metric"><strong>${profile.rewards.streak}</strong><small>${ui().days}</small></div><div class="metric"><strong>${profile.rewards.stars}</strong><small>${ui().stars}</small></div></div><div class="switch-row"><span>${ui().homeLanguage}</span><button class="speaker" data-action="home-language">${homeLanguage.flag} ${homeLanguage.nativeName}</button></div><div class="switch-row"><span>${ui().adSetting}</span><label><input id="ads" type="checkbox" ${profile.preferences.adsEnabled ? 'checked' : ''}> ${ui().on}</label></div><p class="intro">${ui().savedNote}</p></main>${adBanner()}`; bindHeader(); root.querySelector('[data-action="home"]').addEventListener('click', () => { view = 'home'; render(); }); root.querySelector('[data-action="home-language"]').addEventListener('click', () => { languageTarget = 'native'; view = 'languages'; render(); }); root.querySelector('#ads').addEventListener('change', event => { profile.preferences.adsEnabled = event.target.checked; saveProfile(profile); render(); }); }
function bindHeader() { root.querySelector('[data-action="languages"]')?.addEventListener('click', () => { view = 'languages'; render(); }); root.querySelector('[data-action="parent"]')?.addEventListener('click', () => { view = 'parent'; render(); }); if (cloudUser) { const stats = root.querySelector('.stat-row'); if (stats && !stats.querySelector('[data-action="signout"]')) { const button = document.createElement('button'); button.className = 'chip signout'; button.dataset.action = 'signout'; button.textContent = 'Uitloggen'; stats.appendChild(button); } root.querySelector('[data-action="signout"]')?.addEventListener('click', async () => { await signOut(); cloudUser = null; profile.account = null; saveProfile(profile); authMode = 'choice'; view = 'auth'; render(); }); } }
function render() { if (view === 'auth') renderAuth(); else if (view === 'languages') renderLanguages(); else if (view === 'games') renderGames(); else if (view === 'game') renderGame(); else if (view === 'parent') renderParent(); else renderHome(); }
async function boot() { try { const sessionState = await currentSession(); cloudUser = sessionState?.user || null; if (cloudUser) { profile.account = { email: cloudUser.email, provider: 'supabase' }; await syncCloudProgress(); view = profile.selectedLanguage ? (profile.selectedGame ? 'home' : 'games') : 'languages'; } else { profile.account = null; saveProfile(profile); view = 'auth'; } } catch (error) { console.warn('Cloud session unavailable; offline mode remains available.', error); } if ('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(() => {}); render(); }
boot();
