"""Generate Lumio's packaged Persian speech with the Piper Amir voice.

The generator keeps the TTS runtime and model outside the project. It reads the
current Persian curriculum, creates one WAV per word/letter, and writes the JS
manifest used by the app.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = ROOT / "data" / "languages.js"
OUTPUT_DIR = ROOT / "assets" / "audio" / "fa"
MANIFEST = ROOT / "data" / "audio-fa.js"


def filename_for(text: str) -> str:
    codepoints = "-".join(f"{ord(char):x}" for char in text)
    return f"speech-{codepoints}.wav"


def corpus() -> list[str]:
    source = LANGUAGES.read_text(encoding="utf-8")
    words_block = re.search(
        r"const persianWords\s*=\s*\[(.*?)\];\s*function persianLessonWords",
        source,
        re.S,
    )
    if not words_block:
        raise RuntimeError("Could not find persianWords in data/languages.js")

    words = re.findall(r"\['([^']+)'\s*,\s*'[^']*'\]", words_block.group(1))
    letters = list("اآبپتثجچحخدذرزژسشصضطظعغفقکگلمنوهی")
    extras = ["فارسی", "آفرین!"]
    return list(dict.fromkeys([*extras, *letters, *words]))


def main() -> None:
    temp_root = Path(os.environ.get("TEMP", ".")) / "lumio-piper"
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--piper",
        type=Path,
        default=temp_root / "runtime" / "piper" / "piper.exe",
    )
    parser.add_argument(
        "--model",
        type=Path,
        default=temp_root / "fa_IR-amir-medium.onnx",
    )
    args = parser.parse_args()
    if not args.piper.exists() or not args.model.exists():
        raise FileNotFoundError("Piper or the Persian model is missing; see assets/audio/fa/README.md")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for text in corpus():
        output = OUTPUT_DIR / filename_for(text)
        entries.append({"text": text, "output_file": str(output)})

    payload = "\n".join(json.dumps(item, ensure_ascii=False) for item in entries) + "\n"
    subprocess.run(
        [str(args.piper), "--model", str(args.model), "--json-input", "--quiet"],
        input=payload.encode("utf-8"),
        check=True,
    )

    mapping = {
        item["text"]: f"./assets/audio/fa/{Path(item['output_file']).name}"
        for item in entries
    }
    manifest_text = (
        "// Generated by tools/generate-persian-audio.py.\n"
        "export const persianAudio = "
        + json.dumps(mapping, ensure_ascii=False, indent=2)
        + ";\n"
    )
    MANIFEST.write_text(manifest_text, encoding="utf-8")
    print(f"Generated {len(entries)} Persian audio files and {MANIFEST.name}.")


if __name__ == "__main__":
    main()
